version: '2.1'

services:
  oracle11g:
    image: demers/docker-oracle-xe-11g
    container_name: oracle11g
    volumes:
      - "data_work:/home/ubuntu/work"
      - "/home/demers/share:/home/ubuntu/share"
    restart: always
    ports:
      - "22:22"
      - "49161:1521"
      - "27017:27017"
    # A de'commenter pour Linux Ubuntu si ne'cessaire
    # network_mode: "host"

volumes:
  data_work:
